// GENERATED FILE. PLEASE DO NOT EDIT THIS FILE!!

import 'package:routefly/routefly.dart';

import 'app/app_page.dart' as a0;
import 'app/capacitacao/capacitacao_page.dart' as a2;
import 'app/capacitacao/criar_editar_categoria_page.dart' as a14;
import 'app/capacitacao/criar_editar_categoria_transacao_page.dart' as a5;
import 'app/capacitacao/criar_editar_conta_page.dart' as a3;
import 'app/capacitacao/criar_editar_contato_page.dart' as a4;
import 'app/capacitacao/criar_editar_habito_tarefa_page.dart' as a15;
import 'app/capacitacao/criar_editar_transacao_page.dart' as a13;
import 'app/capacitacao/financas/financas_layout.dart' as a12;
import 'app/capacitacao/tarefas_habitos/calendario_page.dart' as a9;
import 'app/capacitacao/tarefas_habitos/categorias_page.dart' as a6;
import 'app/capacitacao/tarefas_habitos/dashboard_page.dart' as a7;
import 'app/capacitacao/tarefas_habitos/habitos_page.dart' as a10;
import 'app/capacitacao/tarefas_habitos/tarefas_habitos_layout.dart' as a8;
import 'app/capacitacao/tarefas_habitos/tarefas_page.dart' as a11;
import 'app/home/home_page.dart' as a16;
import 'app/login/login_page.dart' as a1;

List<RouteEntity> get routes => [
  RouteEntity(
    key: '/',
    uri: Uri.parse('/'),
    routeBuilder: (ctx, settings) =>
        Routefly.defaultRouteBuilder(ctx, settings, const a0.AppPage()),
  ),
  RouteEntity(
    key: '/login',
    uri: Uri.parse('/login'),
    routeBuilder: (ctx, settings) =>
        Routefly.defaultRouteBuilder(ctx, settings, const a1.LoginPage()),
  ),
  RouteEntity(
    key: '/capacitacao',
    uri: Uri.parse('/capacitacao'),
    routeBuilder: (ctx, settings) =>
        Routefly.defaultRouteBuilder(ctx, settings, const a2.CapacitacaoPage()),
  ),
  RouteEntity(
    key: '/capacitacao/criar_editar_conta',
    uri: Uri.parse('/capacitacao/criar_editar_conta'),
    routeBuilder: a3.routeBuilder,
  ),
  RouteEntity(
    key: '/capacitacao/criar_editar_contato',
    uri: Uri.parse('/capacitacao/criar_editar_contato'),
    routeBuilder: a4.routeBuilder,
  ),
  RouteEntity(
    key: '/capacitacao/criar_editar_categoria_transacao',
    uri: Uri.parse('/capacitacao/criar_editar_categoria_transacao'),
    routeBuilder: a5.routeBuilder,
  ),
  RouteEntity(
    key: '/capacitacao/tarefas_habitos/categorias',
    parent: '/capacitacao/tarefas_habitos',
    uri: Uri.parse('/capacitacao/tarefas_habitos/categorias'),
    routeBuilder: (ctx, settings) =>
        Routefly.defaultRouteBuilder(ctx, settings, const a6.CategoriasPage()),
  ),
  RouteEntity(
    key: '/capacitacao/tarefas_habitos/dashboard',
    parent: '/capacitacao/tarefas_habitos',
    uri: Uri.parse('/capacitacao/tarefas_habitos/dashboard'),
    routeBuilder: (ctx, settings) =>
        Routefly.defaultRouteBuilder(ctx, settings, const a7.DashboardPage()),
  ),
  RouteEntity(
    key: '/capacitacao/tarefas_habitos',
    uri: Uri.parse('/capacitacao/tarefas_habitos'),
    routeBuilder: (ctx, settings) =>
        Routefly.defaultRouteBuilder(ctx, settings, const a8.TarefasPage()),
  ),
  RouteEntity(
    key: '/capacitacao/tarefas_habitos/calendario',
    parent: '/capacitacao/tarefas_habitos',
    uri: Uri.parse('/capacitacao/tarefas_habitos/calendario'),
    routeBuilder: (ctx, settings) =>
        Routefly.defaultRouteBuilder(ctx, settings, const a9.CalendarioPage()),
  ),
  RouteEntity(
    key: '/capacitacao/tarefas_habitos/habitos',
    parent: '/capacitacao/tarefas_habitos',
    uri: Uri.parse('/capacitacao/tarefas_habitos/habitos'),
    routeBuilder: (ctx, settings) => Routefly.defaultRouteBuilder(
      ctx,
      settings,
      const a10.HabitosListPage(),
    ),
  ),
  RouteEntity(
    key: '/capacitacao/tarefas_habitos/tarefas',
    parent: '/capacitacao/tarefas_habitos',
    uri: Uri.parse('/capacitacao/tarefas_habitos/tarefas'),
    routeBuilder: (ctx, settings) => Routefly.defaultRouteBuilder(
      ctx,
      settings,
      const a11.TarefasListPage(),
    ),
  ),
  RouteEntity(
    key: '/capacitacao/financas',
    uri: Uri.parse('/capacitacao/financas'),
    routeBuilder: (ctx, settings) =>
        Routefly.defaultRouteBuilder(ctx, settings, const a12.FinancasLayout()),
  ),
  RouteEntity(
    key: '/capacitacao/criar_editar_transacao',
    uri: Uri.parse('/capacitacao/criar_editar_transacao'),
    routeBuilder: a13.routeBuilder,
  ),
  RouteEntity(
    key: '/capacitacao/criar_editar_categoria',
    uri: Uri.parse('/capacitacao/criar_editar_categoria'),
    routeBuilder: (ctx, settings) => Routefly.defaultRouteBuilder(
      ctx,
      settings,
      const a14.CriarEditarCategoriaPage(),
    ),
  ),
  RouteEntity(
    key: '/capacitacao/criar_editar_habito_tarefa',
    uri: Uri.parse('/capacitacao/criar_editar_habito_tarefa'),
    routeBuilder: a15.routeBuilder,
  ),
  RouteEntity(
    key: '/home',
    uri: Uri.parse('/home'),
    routeBuilder: (ctx, settings) =>
        Routefly.defaultRouteBuilder(ctx, settings, const a16.HomePage()),
  ),
];

const routePaths = (
  path: '/',
  login: '/login',
  capacitacao: (
    path: '/capacitacao',
    criarEditarConta: '/capacitacao/criar_editar_conta',
    criarEditarContato: '/capacitacao/criar_editar_contato',
    criarEditarCategoriaTransacao:
        '/capacitacao/criar_editar_categoria_transacao',
    tarefasHabitos: (
      path: '/capacitacao/tarefas_habitos',
      categorias: '/capacitacao/tarefas_habitos/categorias',
      dashboard: '/capacitacao/tarefas_habitos/dashboard',
      calendario: '/capacitacao/tarefas_habitos/calendario',
      habitos: '/capacitacao/tarefas_habitos/habitos',
      tarefas: '/capacitacao/tarefas_habitos/tarefas',
    ),
    financas: '/capacitacao/financas',
    criarEditarTransacao: '/capacitacao/criar_editar_transacao',
    criarEditarCategoria: '/capacitacao/criar_editar_categoria',
    criarEditarHabitoTarefa: '/capacitacao/criar_editar_habito_tarefa',
  ),
  home: '/home',
);
