// GENERATED FILE. PLEASE DO NOT EDIT THIS FILE!!

import 'package:routefly/routefly.dart';

import 'app/app_page.dart' as a0;
import 'app/capacitacao/capacitacao_page.dart' as a1;
import 'app/capacitacao/tarefas/tarefas_page.dart' as a2;
import 'app/home/home_page.dart' as a3;
import 'app/login/login_page.dart' as a4;

List<RouteEntity> get routes => [
      RouteEntity(
        key: '/',
        uri: Uri.parse('/'),
        routeBuilder: (ctx, settings) => Routefly.defaultRouteBuilder(
          ctx,
          settings,
          const a0.AppPage(),
        ),
      ),
      RouteEntity(
        key: '/capacitacao',
        uri: Uri.parse('/capacitacao'),
        routeBuilder: (ctx, settings) => Routefly.defaultRouteBuilder(
          ctx,
          settings,
          const a1.CapacitacaoPage(),
        ),
      ),
      RouteEntity(
        key: '/capacitacao/tarefas',
        uri: Uri.parse('/capacitacao/tarefas'),
        routeBuilder: (ctx, settings) => Routefly.defaultRouteBuilder(
          ctx,
          settings,
          const a2.TarefasPage(),
        ),
      ),
      RouteEntity(
        key: '/home',
        uri: Uri.parse('/home'),
        routeBuilder: (ctx, settings) => Routefly.defaultRouteBuilder(
          ctx,
          settings,
          const a3.HomePage(),
        ),
      ),
      RouteEntity(
        key: '/login',
        uri: Uri.parse('/login'),
        routeBuilder: (ctx, settings) => Routefly.defaultRouteBuilder(
          ctx,
          settings,
          const a4.LoginPage(),
        ),
      ),
    ];

const routePaths = (
  path: '/',
  capacitacao: (
    path: '/capacitacao',
    tarefas: '/capacitacao/tarefas',
  ),
  home: '/home',
  login: '/login',
);
